nk:
  env-key: ts5-platform-beebattle-dev
  env-name: 研发环境 in BeeBattle
  file-root-path: /Users/bean/Downloads/tfms
  compress:
    enabled: false
  component-base-packages:
    - cn.nkpro.ts5.cards
    - cn.nkpro.groovy
  component-disable-online-editing: true
  component-reload-class-path: true
spring:
  datasource:
    url: jdbc:mysql://121.36.76.251:3306/ts5_beebattle_dev
    username: root
    password: VTOZ8clUpSerX6hI
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.99.236.56
    port: 666
    password: 1qazxsw2
  elasticsearch:
    rest:
      uris: [ "http://47.114.120.178:9200" ]
      username:
      password:

