nk:
  env-key: ts5-platform-beebattle-dev
  env-name: 研发环境 in BeeBattle
  file-root-path: /Users/bean/Downloads/tfms
  compress:
    enabled: false
  component-base-packages:
    - cn.nkpro.ts5.cards
    - cn.nkpro.groovy
  component-disable-online-editing: true
  component-reload-class-path: true
spring:
  datasource:
    url: jdbc:mysql://192.168.1.149:3306/ts5_beebattle_dev
    username: root
    password: VTOZ8clUpSerX6hI
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.157
    port: 6379
    password: 1qazxsw2
  elasticsearch:
    rest:
      #uris: [ "http://192.168.1.119:9200" ,"http://192.168.1.119:9201","http://192.168.1.119:9202" ],
      uris: ["http://192.168.1.157:9200"]
      username: elastic
      password: 1qazxsw2

